//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Job
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CurrentCompany { get; set; }
        public byte[] CV { get; set; }
        public string LinkedInURL { get; set; }
        public string TwitterURL { get; set; }
        public string GithubURL { get; set; }
        public string PortfolioURL { get; set; }
        public string OtherWebsite { get; set; }
        public string More { get; set; }
    }
}
