//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List_Game()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string LinkIOS { get; set; }
        public string LinkAndroid { get; set; }
        public string Caption { get; set; }
        public bool Featured_Games { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
