//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGame.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebGameEntities : DbContext
    {
        public WebGameEntities()
            : base("name=WebGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<List_Game> List_Game { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<GameSubmit> GameSubmits { get; set; }
        public virtual DbSet<List_Jobs> List_Jobs { get; set; }
        public virtual DbSet<Apply_Job> Apply_Job { get; set; }
    }
}
